version: "3"
services:
    mongodb:
        image: "mongo:4.4"
        container_name: "mongodb"
        restart: always
        ports:
            - "27017-27019:27017-27019"
        environment:
            MONGO_INITDB_ROOT_USERNAME: doanxem
            MONGO_INITDB_ROOT_PASSWORD: Admin123
            MONGO_INITDB_DATABASE: doanxem
        volumes:
            - ./docker/mongo-entrypoint:/docker-entrypoint-initdb.d
            - ./mongodb_volume:/data/db
